"""
Script tạo dữ liệu mẫu bệnh viện TP.HCM
Chạy: python manage.py shell < create_hospitals_hcmc.py
"""

from hospitals.models import Hospital

# Danh sách bệnh viện TP.HCM (dữ liệu mẫu đầy đủ)
hospitals_data = [
    # QUẬN 1
    {
        'name': 'Bệnh viện Đa khoa Quốc tế Vinmec Central Park',
        'name_en': 'Vinmec Central Park International Hospital',
        'address': '208 Nguyễn Hữu Cảnh, Phường 22, Quận Bình Thạnh, TP.HCM',
        'phone': '028 3622 1166',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology', 'orthopedics', 'pediatrics', 'obstetrics'],
        'emergency_services': True,
        'latitude': 10.8036,
        'longitude': 106.7193,
        'district': 'binhthanh',
        'working_hours': '24/7',
        'website': 'https://vinmec.com',
    },
    {
        'name': 'Bệnh viện Tai Mũi Họng TP.HCM',
        'name_en': 'Ho Chi Minh City ENT Hospital',
        'address': '155-157 Trần Quốc Thảo, Phường 9, Quận 3, TP.HCM',
        'phone': '028 3931 0774',
        'hospital_type': 'public',
        'main_specialty': 'ent',
        'specialties': ['ent', 'head_neck_surgery'],
        'emergency_services': False,
        'latitude': 10.7862,
        'longitude': 106.6861,
        'district': 'quan3',
        'working_hours': '07:00-17:00',
    },
    {
        'name': 'Bệnh viện Từ Dũ',
        'name_en': 'Tu Du Hospital',
        'address': '284 Cống Quỳnh, Phường Phạm Ngũ Lão, Quận 1, TP.HCM',
        'phone': '1900 7122',
        'hospital_type': 'public',
        'main_specialty': 'obstetrics',
        'specialties': ['obstetrics', 'gynecology', 'neonatology', 'infertility'],
        'emergency_services': True,
        'latitude': 10.7665,
        'longitude': 106.6828,
        'district': 'quan1',
        'working_hours': '24/7',
        'website': 'https://tudu.com.vn',
    },
    {
        'name': 'Bệnh viện Hùng Vương',
        'name_en': 'Hung Vuong Hospital',
        'address': '128 Hồng Bàng, Phường 12, Quận 5, TP.HCM',
        'phone': '028 3855 8532',
        'hospital_type': 'public',
        'main_specialty': 'obstetrics',
        'specialties': ['obstetrics', 'gynecology', 'neonatology'],
        'emergency_services': True,
        'latitude': 10.7553,
        'longitude': 106.6617,
        'district': 'quan5',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Ung Bướu TP.HCM (Cơ sở 1)',
        'name_en': 'HCMC Oncology Hospital',
        'address': '3 Nơ Trang Long, Phường 7, Quận Bình Thạnh, TP.HCM',
        'phone': '028 3843 3021',
        'hospital_type': 'public',
        'main_specialty': 'oncology',
        'specialties': ['oncology', 'surgery', 'radiotherapy', 'chemotherapy'],
        'emergency_services': True,
        'latitude': 10.8066,
        'longitude': 106.6961,
        'district': 'binhthanh',
        'working_hours': '05:00-17:00',
    },
    {
        'name': 'Bệnh viện Ung Bướu TP.HCM (Cơ sở 2)',
        'name_en': 'HCMC Oncology Hospital Campus 2',
        'address': 'Đường 400, Ấp Cây Dầu, Phường Tân Phú, TP. Thủ Đức, TP.HCM',
        'phone': '028 3843 3021',
        'hospital_type': 'public',
        'main_specialty': 'oncology',
        'specialties': ['oncology', 'surgery', 'radiotherapy'],
        'emergency_services': True,
        'latitude': 10.8654,
        'longitude': 106.8045,
        'district': 'thuduc',
        'working_hours': '07:00-16:30',
    },
    {
        'name': 'Bệnh viện Phạm Ngọc Thạch',
        'name_en': 'Pham Ngoc Thach Hospital',
        'address': '120 Hùng Vương, Phường 12, Quận 5, TP.HCM',
        'phone': '028 3855 0207',
        'hospital_type': 'public',
        'main_specialty': 'general',
        'specialties': ['respiratory', 'tuberculosis', 'thoracic_surgery'],
        'emergency_services': True,
        'latitude': 10.7565,
        'longitude': 106.6645,
        'district': 'quan5',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Nhân dân Gia Định',
        'name_en': 'Gia Dinh People\'s Hospital',
        'address': '1 Nơ Trang Long, Phường 7, Quận Bình Thạnh, TP.HCM',
        'phone': '028 3841 2692',
        'hospital_type': 'public',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology', 'endocrinology', 'neurology'],
        'emergency_services': True,
        'latitude': 10.8055,
        'longitude': 106.6968,
        'district': 'binhthanh',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Trưng Vương',
        'name_en': 'Trung Vuong Hospital',
        'address': '266 Lý Thường Kiệt, Phường 14, Quận 10, TP.HCM',
        'phone': '028 3865 6744',
        'hospital_type': 'public',
        'main_specialty': 'general',
        'specialties': ['general', 'emergency', 'trauma'],
        'emergency_services': True,
        'latitude': 10.7725,
        'longitude': 106.6578,
        'district': 'quan10',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Nguyễn Tri Phương',
        'name_en': 'Nguyen Tri Phuong Hospital',
        'address': '468 Nguyễn Trãi, Phường 8, Quận 5, TP.HCM',
        'phone': '028 3923 4332',
        'hospital_type': 'public',
        'main_specialty': 'general',
        'specialties': ['general', 'neurology', 'endocrinology', 'dialysis'],
        'emergency_services': True,
        'latitude': 10.7548,
        'longitude': 106.6710,
        'district': 'quan5',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện An Bình',
        'name_en': 'An Binh Hospital',
        'address': '146 An Bình, Phường 7, Quận 5, TP.HCM',
        'phone': '028 3923 4359',
        'hospital_type': 'public',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology', 'surgery'],
        'emergency_services': True,
        'latitude': 10.7535,
        'longitude': 106.6738,
        'district': 'quan5',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Tâm Thần TP.HCM',
        'name_en': 'HCMC Mental Hospital',
        'address': '766 Võ Văn Kiệt, Phường 1, Quận 5, TP.HCM',
        'phone': '028 3923 4675',
        'hospital_type': 'public',
        'main_specialty': 'psychiatry',
        'specialties': ['psychiatry', 'psychology'],
        'emergency_services': True,
        'latitude': 10.7512,
        'longitude': 106.6805,
        'district': 'quan5',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Lê Văn Thịnh (Bệnh viện Quận 2 cũ)',
        'name_en': 'Le Van Thinh Hospital',
        'address': '130 Lê Văn Thịnh, Phường Bình Trưng Tây, TP. Thủ Đức, TP.HCM',
        'phone': '028 3743 2672',
        'hospital_type': 'public',
        'main_specialty': 'general',
        'specialties': ['general', 'surgery', 'obstetrics'],
        'emergency_services': True,
        'latitude': 10.7788,
        'longitude': 106.7622,
        'district': 'thuduc',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Quận 4',
        'name_en': 'District 4 Hospital',
        'address': '63-65 Bến Vân Đồn, Phường 12, Quận 4, TP.HCM',
        'phone': '028 3826 1568',
        'hospital_type': 'public',
        'main_specialty': 'general',
        'specialties': ['general', 'emergency'],
        'emergency_services': True,
        'latitude': 10.7635,
        'longitude': 106.6995,
        'district': 'quan4',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Đa khoa Tân Hưng',
        'name_en': 'Tan Hung General Hospital',
        'address': '87 Trần Xuân Soạn, Phường Tân Hưng, Quận 7, TP.HCM',
        'phone': '028 3776 0648',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'orthopedics', 'surgery'],
        'emergency_services': True,
        'latitude': 10.7515,
        'longitude': 106.7022,
        'district': 'quan7',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Lê Văn Việt (Bệnh viện Quận 9 cũ)',
        'name_en': 'Le Van Viet Hospital',
        'address': '387 Lê Văn Việt, Phường Tăng Nhơn Phú A, TP. Thủ Đức, TP.HCM',
        'phone': '028 3897 3628',
        'hospital_type': 'public',
        'main_specialty': 'general',
        'specialties': ['general', 'emergency'],
        'emergency_services': True,
        'latitude': 10.8458,
        'longitude': 106.7865,
        'district': 'thuduc',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Đa khoa Vạn Hạnh',
        'name_en': 'Van Hanh Hospital',
        'address': '781/B1-B3-B5 Lê Hồng Phong, Phường 12, Quận 10, TP.HCM',
        'phone': '028 3863 2553',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'ivf', 'dentistry'],
        'emergency_services': True,
        'latitude': 10.7768,
        'longitude': 106.6715,
        'district': 'quan10',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Đa khoa Xuyên Á',
        'name_en': 'Xuyen A General Hospital',
        'address': '42 Quốc lộ 22, Ấp Chợ, Xã Tân Phú Trung, Huyện Củ Chi, TP.HCM',
        'phone': '1800 9075',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology', 'neurology'],
        'emergency_services': True,
        'latitude': 10.9575,
        'longitude': 106.5458,
        'district': 'cuchi',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Huyện Bình Chánh',
        'name_en': 'Binh Chanh District Hospital',
        'address': 'Số 1, Đường số 1, Khu trung tâm hành chính Huyện, Tân Túc, Bình Chánh, TP.HCM',
        'phone': '028 3760 0306',
        'hospital_type': 'public',
        'main_specialty': 'general',
        'specialties': ['general', 'emergency'],
        'emergency_services': True,
        'latitude': 10.6865,
        'longitude': 106.5925,
        'district': 'binhchanh',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Nhi đồng Thành phố (Bình Chánh)',
        'name_en': 'City Children\'s Hospital',
        'address': '15 Võ Trần Chí, Tân Kiên, Bình Chánh, TP.HCM',
        'phone': '028 2253 6688',
        'hospital_type': 'public',
        'main_specialty': 'pediatrics',
        'specialties': ['pediatrics', 'oncology_pediatrics', 'surgery'],
        'emergency_services': True,
        'latitude': 10.7250,
        'longitude': 106.5910,
        'district': 'binhchanh',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Gia An 115',
        'name_en': 'Gia An 115 Hospital',
        'address': 'Số 05, Đường 17A, Phường Bình Trị Đông B, Quận Bình Tân, TP.HCM',
        'phone': '028 6288 5886',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology', 'stroke'],
        'emergency_services': True,
        'latitude': 10.7554,
        'longitude': 106.6080,
        'district': 'binhtan',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Quốc tế City (CIH)',
        'name_en': 'City International Hospital',
        'address': 'Số 3, Đường 17A, Phường Bình Trị Đông B, Quận Bình Tân, TP.HCM',
        'phone': '028 6280 3333',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'obtetrics', 'pediatrics'],
        'emergency_services': True,
        'latitude': 10.7562,
        'longitude': 106.6095,
        'district': 'binhtan',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Hoàn Mỹ Sài Gòn',
        'name_en': 'Hoan My Saigon Hospital',
        'address': '60-60A Phan Xích Long, Phường 1, Quận Phú Nhuận, TP.HCM',
        'phone': '028 3990 2468',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology', 'gastroenterology'],
        'emergency_services': True,
        'latitude': 10.7965,
        'longitude': 106.6855,
        'district': 'phunhuan',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Đa khoa Tâm Anh TP.HCM',
        'name_en': 'Tam Anh General Hospital',
        'address': '2B Phổ Quang, Phường 2, Quận Tân Bình, TP.HCM',
        'phone': '028 7102 6789',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'ivf', 'orthopedics', 'pediatrics'],
        'emergency_services': True,
        'latitude': 10.8062,
        'longitude': 106.6668,
        'district': 'tanbinh',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Quân Dân Y Miền Đông',
        'name_en': 'Eastern Military-Civil Hospital',
        'address': '50 Lê Văn Việt, Phường Hiệp Phú, TP. Thủ Đức, TP.HCM',
        'phone': '028 3896 0054',
        'hospital_type': 'public',
        'main_specialty': 'general',
        'specialties': ['general', 'trauma'],
        'emergency_services': True,
        'latitude': 10.8465,
        'longitude': 106.7765,
        'district': 'thuduc',
        'working_hours': '24/7',
    },
    {
        'name': 'Phòng khám Victoria Healthcare (Q7)',
        'name_en': 'Victoria Healthcare Clinic D7',
        'address': '1056 Nguyễn Văn Linh, Sky Garden 1, Phú Mỹ Hưng, Quận 7, TP.HCM',
        'phone': '028 3910 4545',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'pediatrics'],
        'emergency_services': False,
        'latitude': 10.7285,
        'longitude': 106.7095,
        'district': 'quan7',
        'working_hours': '08:00-20:00',
    },
    {
        'name': 'Phòng khám Quốc tế CarePlus (Q7)',
        'name_en': 'CarePlus International Clinic',
        'address': 'Lầu 2, Crescent Plaza, 105 Tôn Dật Tiên, Quận 7, TP.HCM',
        'phone': '1800 6116',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology', 'pediatrics'],
        'emergency_services': False,
        'latitude': 10.7295,
        'longitude': 106.7190,
        'district': 'quan7',
        'working_hours': '08:00-17:00 (CN nghỉ)',
    },
    {
        'name': 'Phòng khám Quốc tế CarePlus (Tân Bình)',
        'name_en': 'CarePlus International Clinic Tan Binh',
        'address': '107 Tân Hải, Phường 13, Quận Tân Bình, TP.HCM',
        'phone': '1800 6116',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'pediatrics'],
        'emergency_services': False,
        'latitude': 10.8035,
        'longitude': 106.6455,
        'district': 'tanbinh',
        'working_hours': '08:00-20:00',
    },
    {
        'name': 'Phòng khám Marie Stopes (Tân Bình)',
        'name_en': 'Marie Stopes International',
        'address': '307/15 Nguyễn Văn Trỗi, Phường 1, Quận Tân Bình, TP.HCM',
        'phone': '1900 55 88 82',
        'hospital_type': 'clinic',
        'main_specialty': 'obstetrics',
        'specialties': ['obstetrics', 'gynecology', 'family_planning'],
        'emergency_services': False,
        'latitude': 10.7985,
        'longitude': 106.6650,
        'district': 'tanbinh',
        'working_hours': '08:00-17:00',
    },
    {
        'name': 'Phòng khám Nhi khoa Nancy',
        'name_en': 'Nancy Pediatric Clinic',
        'address': '615A Trần Hưng Đạo, Phường 1, Quận 5, TP.HCM',
        'phone': '028 3838 2155',
        'hospital_type': 'clinic',
        'main_specialty': 'pediatrics',
        'specialties': ['pediatrics', 'vaccination'],
        'emergency_services': True,
        'latitude': 10.7525,
        'longitude': 106.6800,
        'district': 'quan5',
        'working_hours': '24/7',
    },
    {
        'name': 'Phòng khám Đa khoa Sài Gòn',
        'name_en': 'Saigon General Clinic',
        'address': '124 Hải Thượng Lãn Ông, Phường 10, Quận 5, TP.HCM',
        'phone': '028 3855 0500',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general'],
        'emergency_services': False,
        'latitude': 10.7510,
        'longitude': 106.6620,
        'district': 'quan5',
        'working_hours': '07:30-16:30',
    },
    {
        'name': 'Phòng khám Hoàn Mỹ Sài Gòn (Thủ Đức)',
        'name_en': 'Hoan My Clinic Thu Duc',
        'address': '241 Quốc lộ 1K, Phường Linh Xuân, TP. Thủ Đức, TP.HCM',
        'phone': '028 3724 0368',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general'],
        'emergency_services': False,
        'latitude': 10.8750,
        'longitude': 106.7650,
        'district': 'thuduc',
        'working_hours': '07:00-16:30',
    },
    {
        'name': 'Bệnh viện Mắt Cao Thắng',
        'name_en': 'Cao Thang Eye Hospital',
        'address': '135B Trần Bình Trọng, Phường 2, Quận 5, TP.HCM',
        'phone': '028 3923 8435',
        'hospital_type': 'private',
        'main_specialty': 'ophthalmology',
        'specialties': ['ophthalmology', 'lasik'],
        'emergency_services': False,
        'latitude': 10.7585,
        'longitude': 106.6775,
        'district': 'quan5',
        'working_hours': '07:00-17:00',
    },
    {
        'name': 'Bệnh viện SAIGON-ITO Phú Nhuận',
        'name_en': 'SAIGON-ITO Hospital Phu Nhuan',
        'address': '140C Nguyễn Trọng Tuyển, Phường 8, Quận Phú Nhuận, TP.HCM',
        'phone': '028 3844 1399',
        'hospital_type': 'private',
        'main_specialty': 'orthopedics',
        'specialties': ['orthopedics', 'trauma'],
        'emergency_services': True,
        'latitude': 10.8005,
        'longitude': 106.6750,
        'district': 'phunhuan',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Đa khoa Hồng Đức III',
        'name_en': 'Hong Duc General Hospital III',
        'address': '32/2 Thống Nhất, Phường 10, Quận Gò Vấp, TP.HCM',
        'phone': '028 3996 9999',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology'],
        'emergency_services': True,
        'latitude': 10.8350,
        'longitude': 106.6650,
        'district': 'govap',
        'working_hours': '24/7',
    },
    {
        'name': 'Bệnh viện Đa khoa Tâm Trí Sài Gòn',
        'name_en': 'Tam Tri Saigon General Hospital',
        'address': '171/3 Trường Chinh, Phường Tân Thới Nhất, Quận 12, TP.HCM',
        'phone': '028 6260 1100',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'emergency'],
        'emergency_services': True,
        'latitude': 10.8250,
        'longitude': 106.6150,
        'district': 'quan12',
        'working_hours': '24/7',
    },

    # --- HỆ THỐNG TIÊM CHỦNG VNVC (10+ CƠ SỞ) ---
    {
        'name': 'VNVC Hoàng Văn Thụ',
        'name_en': 'VNVC Hoang Van Thu',
        'address': '198 Hoàng Văn Thụ, Phường 9, Quận Phú Nhuận, TP.HCM',
        'phone': '028 7102 6595',
        'hospital_type': 'clinic',
        'main_specialty': 'preventive_medicine',
        'specialties': ['vaccination', 'pediatrics'],
        'emergency_services': False,
        'latitude': 10.8005,
        'longitude': 106.6785,
        'district': 'phunhuan',
        'working_hours': '07:30-17:00'
    },
    {
        'name': 'VNVC Cantavil An Phú',
        'name_en': 'VNVC Cantavil An Phu',
        'address': 'Lầu 1, TTTM Cantavil An Phú, 1 Song Hành, Phường An Phú, TP. Thủ Đức, TP.HCM',
        'phone': '028 7102 6595',
        'hospital_type': 'clinic',
        'main_specialty': 'preventive_medicine',
        'specialties': ['vaccination'],
        'emergency_services': False,
        'latitude': 10.8015,
        'longitude': 106.7420,
        'district': 'thuduc',
        'working_hours': '07:30-17:00'
    },
    {
        'name': 'VNVC Lê Đại Hành',
        'name_en': 'VNVC Le Dai Hanh',
        'address': 'Lầu 1, TTTM Flemington, 184 Lê Đại Hành, Phường 15, Quận 11, TP.HCM',
        'phone': '028 7102 6595',
        'hospital_type': 'clinic',
        'main_specialty': 'preventive_medicine',
        'specialties': ['vaccination'],
        'emergency_services': False,
        'latitude': 10.7685,
        'longitude': 106.6575,
        'district': 'quan11',
        'working_hours': '07:30-17:00'
    },
    {
        'name': 'VNVC Gò Vấp',
        'name_en': 'VNVC Go Vap',
        'address': '408 Nguyễn Xí, Phường 13, Quận Bình Thạnh, TP.HCM',
        'phone': '028 7102 6595',
        'hospital_type': 'clinic',
        'main_specialty': 'preventive_medicine',
        'specialties': ['vaccination'],
        'emergency_services': False,
        'latitude': 10.8122,
        'longitude': 106.7035,
        'district': 'binhthanh',
        'working_hours': '07:30-17:00'
    },
    {
        'name': 'VNVC Bình Tân',
        'name_en': 'VNVC Binh Tan',
        'address': '249 Hương Lộ 3, Phường Sơn Kỳ, Quận Tân Phú, TP.HCM',
        'phone': '028 7102 6595',
        'hospital_type': 'clinic',
        'main_specialty': 'preventive_medicine',
        'specialties': ['vaccination'],
        'emergency_services': False,
        'latitude': 10.8055,
        'longitude': 106.6155,
        'district': 'tanphu',
        'working_hours': '07:30-17:00'
    },

    # --- HỆ THỐNG XÉT NGHIỆM DIAG (5+ CƠ SỞ) ---
    {
        'name': 'Diag Center Cao Thắng',
        'name_en': 'Diag Center Cao Thang',
        'address': '414-420 Cao Thắng, Phường 12, Quận 10, TP.HCM',
        'phone': '1900 1717',
        'hospital_type': 'clinic',
        'main_specialty': 'laboratory',
        'specialties': ['laboratory', 'health_check'],
        'emergency_services': False,
        'latitude': 10.7780,
        'longitude': 106.6755,
        'district': 'quan10',
        'working_hours': '06:00-19:00'
    },
    {
        'name': 'Diag Center Nguyễn Trãi',
        'name_en': 'Diag Center Nguyen Trai',
        'address': '231 Nguyễn Trãi, Phường Nguyễn Cư Trinh, Quận 1, TP.HCM',
        'phone': '1900 1717',
        'hospital_type': 'clinic',
        'main_specialty': 'laboratory',
        'specialties': ['laboratory'],
        'emergency_services': False,
        'latitude': 10.7645,
        'longitude': 106.6870,
        'district': 'quan1',
        'working_hours': '06:00-19:00'
    },
    {
        'name': 'Diag Center Phú Mỹ Hưng',
        'name_en': 'Diag Center Phu My Hung',
        'address': '48 Đặng Đức Thuật, Phường Tân Phong, Quận 7, TP.HCM',
        'phone': '1900 1717',
        'hospital_type': 'clinic',
        'main_specialty': 'laboratory',
        'specialties': ['laboratory'],
        'emergency_services': False,
        'latitude': 10.7325,
        'longitude': 106.7085,
        'district': 'quan7',
        'working_hours': '06:00-19:00'
    },
    {
        'name': 'Diag Center Thảo Điền',
        'name_en': 'Diag Center Thao Dien',
        'address': '26 Thảo Điền, Phường Thảo Điền, TP. Thủ Đức, TP.HCM',
        'phone': '1900 1717',
        'hospital_type': 'clinic',
        'main_specialty': 'laboratory',
        'specialties': ['laboratory'],
        'emergency_services': False,
        'latitude': 10.8030,
        'longitude': 106.7380,
        'district': 'thuduc',
        'working_hours': '06:00-19:00'
    },
    {
        'name': 'Bệnh viện Quân y 175',
        'name_en': 'Military Hospital 175',
        'address': '786 Nguyễn Kiệm, Phường 3, Quận Gò Vấp, TP.HCM',
        'phone': '1900 1175',
        'hospital_type': 'public',
        'main_specialty': 'general',
        'specialties': ['general', 'trauma', 'oncology', 'orthopedics'],
        'emergency_services': True,
        'latitude': 10.8175,
        'longitude': 106.6780,
        'district': 'govap',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Triều An',
        'name_en': 'Trieu An Hospital',
        'address': '425 Kinh Dương Vương, Phường An Lạc, Quận Bình Tân, TP.HCM',
        'phone': '028 3750 9999',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology', 'obstetrics'],
        'emergency_services': True,
        'latitude': 10.7435,
        'longitude': 106.6085,
        'district': 'binhtan',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Huyện Cần Giờ',
        'name_en': 'Can Gio District Hospital',
        'address': 'Duyên Hải, Thị trấn Cần Thạnh, Huyện Cần Giờ, TP.HCM',
        'phone': '028 3874 0318',
        'hospital_type': 'public',
        'main_specialty': 'general',
        'specialties': ['general', 'emergency'],
        'emergency_services': True,
        'latitude': 10.4075,
        'longitude': 106.9530,
        'district': 'cangio',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Phục hồi Chức năng - Điều trị Bệnh nghề nghiệp',
        'name_en': 'Rehabilitation Hospital',
        'address': '313 Âu Dương Lân, Phường 2, Quận 8, TP.HCM',
        'phone': '028 3856 9147',
        'hospital_type': 'public',
        'main_specialty': 'rehabilitation',
        'specialties': ['rehabilitation', 'occupational_therapy'],
        'emergency_services': False,
        'latitude': 10.7380,
        'longitude': 106.6855,
        'district': 'quan8',
        'working_hours': '07:30-16:30'
    },
    {
        'name': 'Viện Y Dược Học Dân Tộc TP.HCM',
        'name_en': 'Institute of Traditional Medicine',
        'address': '273 Nguyễn Văn Trỗi, Phường 10, Quận Phú Nhuận, TP.HCM',
        'phone': '028 3844 3047',
        'hospital_type': 'public',
        'main_specialty': 'traditional_medicine',
        'specialties': ['traditional_medicine', 'acupuncture'],
        'emergency_services': True,
        'latitude': 10.7955,
        'longitude': 106.6740,
        'district': 'phunhuan',
        'working_hours': '07:00-17:00'
    },
    {
        'name': 'Bệnh viện Răng Hàm Mặt Trung Ương TP.HCM',
        'name_en': 'National Hospital of Odonto-Stomatology',
        'address': '201A Nguyễn Chí Thanh, Phường 12, Quận 5, TP.HCM',
        'phone': '028 3855 6732',
        'hospital_type': 'public',
        'main_specialty': 'dentistry',
        'specialties': ['dentistry', 'maxillofacial_surgery'],
        'emergency_services': True,
        'latitude': 10.7570,
        'longitude': 106.6625,
        'district': 'quan5',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Truyền máu Huyết học (Cơ sở 2)',
        'name_en': 'Blood Transfusion Hematology Hospital',
        'address': 'Số 1 Trần Hữu Nghiệp, Tân Kiên, Bình Chánh, TP.HCM',
        'phone': '028 3839 7535',
        'hospital_type': 'public',
        'main_specialty': 'hematology',
        'specialties': ['hematology', 'blood_bank'],
        'emergency_services': True,
        'latitude': 10.7240,
        'longitude': 106.5920,
        'district': 'binhchanh',
        'working_hours': '24/7'
    },
    {
        'name': 'Trung tâm Y tế Quận 6',
        'name_en': 'District 6 Health Center',
        'address': 'A5/22 Chợ Lớn, Phường 11, Quận 6, TP.HCM',
        'phone': '028 3751 5564',
        'hospital_type': 'public',
        'main_specialty': 'general',
        'specialties': ['preventive_medicine', 'general'],
        'emergency_services': True,
        'latitude': 10.7455,
        'longitude': 106.6260,
        'district': 'quan6',
        'working_hours': '24/7'
    },
    {
        'name': 'Trạm Y tế Phường Thảo Điền',
        'name_en': 'Thao Dien Ward Health Station',
        'address': '36 Nguyễn Văn Hưởng, Thảo Điền, TP. Thủ Đức, TP.HCM',
        'phone': '028 3744 2668',
        'hospital_type': 'public',
        'main_specialty': 'primary_care',
        'specialties': ['primary_care', 'vaccination'],
        'emergency_services': False,
        'latitude': 10.8060,
        'longitude': 106.7350,
        'district': 'thuduc',
        'working_hours': '07:30-16:30'
    },
    {
        'name': 'Bệnh viện Đa khoa Quốc tế Hạnh Phúc',
        'name_en': 'Hanh Phuc International Hospital',
        'address': '18 Đại lộ Bình Dương, Thuận An (Giáp ranh Thủ Đức)',
        'phone': '1900 6765',
        'hospital_type': 'private',
        'main_specialty': 'obstetrics',
        'specialties': ['obstetrics', 'pediatrics', 'ivf'],
        'emergency_services': True,
        'latitude': 10.8935,
        'longitude': 106.7035,
        'district': 'thuduc',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Quốc tế Mỹ (AIH)',
        'name_en': 'American International Hospital',
        'address': '199 Nguyễn Hoàng, Phường An Phú, TP. Thủ Đức, TP.HCM',
        'phone': '028 3910 9999',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'obstetrics', 'pediatrics', 'gastroenterology'],
        'emergency_services': True,
        'latitude': 10.7975,
        'longitude': 106.7530,
        'district': 'thuduc',
        'working_hours': '24/7'
    },
    {
        'name': 'Phòng khám Đa khoa Tân Quy (Củ Chi)',
        'name_en': 'Tan Quy Regional General Clinic',
        'address': 'TL8, Xã Tân Thạnh Tây, Huyện Củ Chi, TP.HCM',
        'phone': '028 3795 3658',
        'hospital_type': 'public',
        'main_specialty': 'general',
        'specialties': ['general', 'emergency'],
        'emergency_services': True,
        'latitude': 10.9850,
        'longitude': 106.6080,
        'district': 'cuchi',
        'working_hours': '24/7'
    },
    {
        'name': 'Phòng khám Đa khoa Bà Điểm (Hóc Môn)',
        'name_en': 'Ba Diem Clinic',
        'address': '34/3B Nguyễn Ảnh Thủ, Xã Bà Điểm, Huyện Hóc Môn, TP.HCM',
        'phone': '028 3712 6625',
        'hospital_type': 'public',
        'main_specialty': 'general',
        'specialties': ['general', 'emergency'],
        'emergency_services': True,
        'latitude': 10.8450,
        'longitude': 106.6050,
        'district': 'hocmon',
        'working_hours': '24/7'
    },
    {
        'name': 'Trạm Y tế xã Vĩnh Lộc B (Bình Chánh)',
        'name_en': 'Vinh Loc B Health Station',
        'address': 'D2/12B Ấp 4, Xã Vĩnh Lộc B, Huyện Bình Chánh, TP.HCM',
        'phone': '028 3765 2404',
        'hospital_type': 'public',
        'main_specialty': 'primary_care',
        'specialties': ['primary_care', 'vaccination'],
        'emergency_services': False,
        'latitude': 10.7950,
        'longitude': 106.5750,
        'district': 'binhchanh',
        'working_hours': '07:30-16:30'
    },

    # === 50 BỆNH VIỆN VÀ PHÒNG KHÁM TƯ NHÂN MỚI BỔ SUNG ===
    
    # Bệnh viện Tư nhân
    {
        'name': 'Bệnh viện Đa khoa Phương Chi',
        'name_en': 'Phuong Chi General Hospital',
        'address': 'Thửa đất số 172, Đường DX76, Khu phố Định Hòa 2, Phường Chánh Hiệp, Quận 12, TP.HCM',
        'phone': '028 3715 2345',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'surgery', 'obstetrics', 'pediatrics'],
        'emergency_services': True,
        'latitude': 10.8650,
        'longitude': 106.6050,
        'district': 'quan12',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Đa khoa Hồng Đức II',
        'name_en': 'Hong Duc II General Hospital',
        'address': '259 An Phú Đông 3, Khu phố 5, Phường An Phú Đông, Quận 12, TP.HCM',
        'phone': '028 3996 9999',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology', 'orthopedics'],
        'emergency_services': True,
        'latitude': 10.8320,
        'longitude': 106.6280,
        'district': 'quan12',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Đa khoa Hồng Đức IV',
        'name_en': 'Hong Duc IV General Hospital',
        'address': '178 Nguyễn Ảnh Thủ, Phường Trung Mỹ Tây, Quận 12, TP.HCM',
        'phone': '028 6256 8888',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'emergency', 'trauma'],
        'emergency_services': True,
        'latitude': 10.8580,
        'longitude': 106.6120,
        'district': 'quan12',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Đa khoa Nam Sài Gòn',
        'name_en': 'Nam Sai Gon General Hospital',
        'address': '88 Đào Sư Tích, Xã Phước Lộc, Huyện Nhà Bè, TP.HCM',
        'phone': '028 3781 2222',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology', 'gastroenterology'],
        'emergency_services': True,
        'latitude': 10.6650,
        'longitude': 106.7320,
        'district': 'nhabe',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Đa khoa Nhân Ái',
        'name_en': 'Nhan Ai General Hospital',
        'address': '1251 Huỳnh Tấn Phát, Phường Phú Thuận, Quận 7, TP.HCM',
        'phone': '028 3773 9888',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'rehabilitation', 'elderly_care'],
        'emergency_services': True,
        'latitude': 10.7350,
        'longitude': 106.7380,
        'district': 'quan7',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Mắt Sài Gòn',
        'name_en': 'Sai Gon Eye Hospital',
        'address': '473-475 Lê Văn Sỹ, Phường 12, Quận 3, TP.HCM',
        'phone': '028 3862 3355',
        'hospital_type': 'private',
        'main_specialty': 'ophthalmology',
        'specialties': ['ophthalmology', 'lasik', 'cataract'],
        'emergency_services': False,
        'latitude': 10.7850,
        'longitude': 106.6920,
        'district': 'quan3',
        'working_hours': '07:00-18:00'
    },
    {
        'name': 'Bệnh viện Mắt Hà Nội - Chi nhánh TP.HCM',
        'name_en': 'Hanoi Eye Hospital HCMC',
        'address': '108 Lê Hồng Phong, Phường 6, Quận 5, TP.HCM',
        'phone': '028 3955 1555',
        'hospital_type': 'private',
        'main_specialty': 'ophthalmology',
        'specialties': ['ophthalmology', 'retina', 'glaucoma'],
        'emergency_services': False,
        'latitude': 10.7590,
        'longitude': 106.6670,
        'district': 'quan5',
        'working_hours': '07:30-17:30'
    },
    {
        'name': 'Bệnh viện Răng Hàm Mặt Sài Gòn',
        'name_en': 'Sai Gon Odonto-Stomatology Hospital',
        'address': '175 Đường 3/2, Phường 11, Quận 10, TP.HCM',
        'phone': '028 3927 7788',
        'hospital_type': 'private',
        'main_specialty': 'dentistry',
        'specialties': ['dentistry', 'orthodontics', 'implant'],
        'emergency_services': False,
        'latitude': 10.7690,
        'longitude': 106.6780,
        'district': 'quan10',
        'working_hours': '08:00-18:00'
    },
    {
        'name': 'Bệnh viện Da liễu Sài Gòn',
        'name_en': 'Sai Gon Dermatology Hospital',
        'address': '33 Hoàng Hoa Thám, Phường 6, Quận Tân Bình, TP.HCM',
        'phone': '028 3990 5678',
        'hospital_type': 'private',
        'main_specialty': 'dermatology',
        'specialties': ['dermatology', 'laser', 'aesthetic'],
        'emergency_services': False,
        'latitude': 10.7949,
        'longitude': 106.6525,
        'district': 'tanbinh',
        'working_hours': '07:30-17:00'
    },
    {
        'name': 'Bệnh viện Tim Sài Gòn',
        'name_en': 'Sai Gon Heart Hospital',
        'address': '200 Quốc lộ 13, Phường 26, Quận Bình Thạnh, TP.HCM',
        'phone': '028 3516 7890',
        'hospital_type': 'private',
        'main_specialty': 'cardiology',
        'specialties': ['cardiology', 'interventional_cardiology', 'cardiac_surgery'],
        'emergency_services': True,
        'latitude': 10.8080,
        'longitude': 106.7080,
        'district': 'binhthanh',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Ung Bướu Sài Gòn',
        'name_en': 'Sai Gon Oncology Hospital',
        'address': '32 Hồng Bàng, Phường 12, Quận 5, TP.HCM',
        'phone': '028 3955 7888',
        'hospital_type': 'private',
        'main_specialty': 'oncology',
        'specialties': ['oncology', 'chemotherapy', 'radiotherapy'],
        'emergency_services': True,
        'latitude': 10.7550,
        'longitude': 106.6600,
        'district': 'quan5',
        'working_hours': '07:00-17:00'
    },
    {
        'name': 'Bệnh viện Nhi Sài Gòn',
        'name_en': 'Sai Gon Children Hospital',
        'address': '15 Nguyễn Đình Chiểu, Phường 6, Quận 3, TP.HCM',
        'phone': '028 3930 6789',
        'hospital_type': 'private',
        'main_specialty': 'pediatrics',
        'specialties': ['pediatrics', 'neonatology', 'vaccination'],
        'emergency_services': True,
        'latitude': 10.7830,
        'longitude': 106.6830,
        'district': 'quan3',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Sản Nhi Sài Gòn',
        'name_en': 'Sai Gon Obstetrics Gynecology Hospital',
        'address': '58 Đường 3/2, Phường 11, Quận 10, TP.HCM',
        'phone': '028 3962 8899',
        'hospital_type': 'private',
        'main_specialty': 'obstetrics',
        'specialties': ['obstetrics', 'gynecology', 'infertility'],
        'emergency_services': True,
        'latitude': 10.7710,
        'longitude': 106.6800,
        'district': 'quan10',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Đa khoa Thế Kỷ',
        'name_en': 'The Ky Century Hospital',
        'address': '8 Đường số 3, Phường Bình Trị Đông A, Quận Bình Tân, TP.HCM',
        'phone': '028 6260 7777',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology', 'orthopedics'],
        'emergency_services': True,
        'latitude': 10.7620,
        'longitude': 106.5980,
        'district': 'binhtan',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Đa khoa Phước Long',
        'name_en': 'Phuoc Long General Hospital',
        'address': '152 Đường Võ Văn Ngân, Phường Bình Thọ, TP. Thủ Đức, TP.HCM',
        'phone': '028 3896 1234',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'surgery', 'emergency'],
        'emergency_services': True,
        'latitude': 10.8520,
        'longitude': 106.7580,
        'district': 'thuduc',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Đa khoa 115 Gia Định',
        'name_en': '115 Gia Dinh Hospital',
        'address': '33 Xô Viết Nghệ Tĩnh, Phường 24, Quận Bình Thạnh, TP.HCM',
        'phone': '028 3840 5115',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology', 'neurology'],
        'emergency_services': True,
        'latitude': 10.8020,
        'longitude': 106.7020,
        'district': 'binhthanh',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Đa khoa Quang Minh',
        'name_en': 'Quang Minh General Hospital',
        'address': '158 Đường 138, Phường Tân Quý, Quận Tân Phú, TP.HCM',
        'phone': '028 3812 3456',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'orthopedics', 'rehabilitation'],
        'emergency_services': True,
        'latitude': 10.7850,
        'longitude': 106.6280,
        'district': 'tanphu',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Đa khoa Tân Bình',
        'name_en': 'Tan Binh General Hospital',
        'address': '218 Hoàng Văn Thụ, Phường 9, Quận Phú Nhuận, TP.HCM',
        'phone': '028 3844 5566',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology', 'gastroenterology'],
        'emergency_services': True,
        'latitude': 10.7980,
        'longitude': 106.6750,
        'district': 'phunhuan',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Đa khoa Gia Định',
        'name_en': 'Gia Dinh General Hospital',
        'address': '1 Lê Duẩn, Phường Bến Nghé, Quận 1, TP.HCM',
        'phone': '028 3822 8888',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'obstetrics', 'pediatrics'],
        'emergency_services': True,
        'latitude': 10.7730,
        'longitude': 106.6930,
        'district': 'quan1',
        'working_hours': '24/7'
    },
    {
        'name': 'Bệnh viện Đa khoa Hùng Vương',
        'name_en': 'Hung Vuong General Hospital',
        'address': '686 Lạc Long Quân, Phường 10, Quận Tân Bình, TP.HCM',
        'phone': '028 3962 3456',
        'hospital_type': 'private',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology', 'endocrinology'],
        'emergency_services': True,
        'latitude': 10.7950,
        'longitude': 106.6550,
        'district': 'tanbinh',
        'working_hours': '24/7'
    },

    # Phòng khám Tư nhân
    {
        'name': 'Phòng khám Đa khoa Tâm An',
        'name_en': 'Tam An General Clinic',
        'address': '102 Nguyễn Thị Minh Khai, Phường 6, Quận 1, TP.HCM',
        'phone': '028 3825 6789',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'health_check'],
        'emergency_services': False,
        'latitude': 10.7710,
        'longitude': 106.6920,
        'district': 'quan1',
        'working_hours': '07:30-17:00'
    },
    {
        'name': 'Phòng khám Đa khoa Hạnh Phúc',
        'name_en': 'Hanh Phuc General Clinic',
        'address': '85 Bà Huyện Thanh Quan, Phường 9, Quận 3, TP.HCM',
        'phone': '028 3930 7777',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'pediatrics'],
        'emergency_services': False,
        'latitude': 10.7860,
        'longitude': 106.6880,
        'district': 'quan3',
        'working_hours': '08:00-18:00'
    },
    {
        'name': 'Phòng khám Đa khoa Đại Phước',
        'name_en': 'Dai Phuoc General Clinic',
        'address': '21 Đường 3/2, Phường 11, Quận 10, TP.HCM',
        'phone': '028 3868 9999',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology'],
        'emergency_services': False,
        'latitude': 10.7700,
        'longitude': 106.6820,
        'district': 'quan10',
        'working_hours': '07:00-17:00'
    },
    {
        'name': 'Phòng khám Đa khoa Việt Mỹ',
        'name_en': 'Viet My General Clinic',
        'address': '158 Võ Văn Kiệt, Phường 6, Quận 5, TP.HCM',
        'phone': '028 3854 1234',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'gastroenterology'],
        'emergency_services': False,
        'latitude': 10.7570,
        'longitude': 106.6720,
        'district': 'quan5',
        'working_hours': '07:30-17:30'
    },
    {
        'name': 'Phòng khám Đa khoa Nhật Anh',
        'name_en': 'Nhat Anh General Clinic',
        'address': '205 Nguyễn Xí, Phường 26, Quận Bình Thạnh, TP.HCM',
        'phone': '028 3516 7890',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'orthopedics'],
        'emergency_services': False,
        'latitude': 10.8050,
        'longitude': 106.7100,
        'district': 'binhthanh',
        'working_hours': '08:00-17:00'
    },
    {
        'name': 'Phòng khám Đa khoa Bảo Việt',
        'name_en': 'Bao Viet General Clinic',
        'address': '89 Trần Hưng Đạo, Phường Cầu Ông Lãnh, Quận 1, TP.HCM',
        'phone': '028 3910 1234',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'health_check'],
        'emergency_services': False,
        'latitude': 10.7670,
        'longitude': 106.6930,
        'district': 'quan1',
        'working_hours': '07:00-16:30'
    },
    {
        'name': 'Phòng khám Đa khoa Thành Công',
        'name_en': 'Thanh Cong General Clinic',
        'address': '168 Võ Văn Ngân, Phường Bình Thọ, TP. Thủ Đức, TP.HCM',
        'phone': '028 3898 5678',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'pediatrics'],
        'emergency_services': False,
        'latitude': 10.8550,
        'longitude': 106.7600,
        'district': 'thuduc',
        'working_hours': '07:30-17:00'
    },
    {
        'name': 'Phòng khám Đa khoa Phú Cường',
        'name_en': 'Phu Cuong General Clinic',
        'address': '123 Lê Văn Sỹ, Phường 13, Quận Phú Nhuận, TP.HCM',
        'phone': '028 3844 8888',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology'],
        'emergency_services': False,
        'latitude': 10.7950,
        'longitude': 106.6800,
        'district': 'phunhuan',
        'working_hours': '08:00-17:00'
    },
    {
        'name': 'Phòng khám Đa khoa Đông Á',
        'name_en': 'Dong A General Clinic',
        'address': '45 Hoàng Văn Thụ, Phường 8, Quận Phú Nhuận, TP.HCM',
        'phone': '028 3990 2345',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'dermatology'],
        'emergency_services': False,
        'latitude': 10.7930,
        'longitude': 106.6730,
        'district': 'phunhuan',
        'working_hours': '07:30-17:00'
    },
    {
        'name': 'Phòng khám Đa khoa Số 1',
        'name_en': 'Number 1 General Clinic',
        'address': '77 Điện Biên Phủ, Phường Đakao, Quận 1, TP.HCM',
        'phone': '028 3822 5555',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'health_check'],
        'emergency_services': False,
        'latitude': 10.7790,
        'longitude': 106.6950,
        'district': 'quan1',
        'working_hours': '07:00-17:00'
    },
    {
        'name': 'Phòng khám Nhi khoa Sài Gòn',
        'name_en': 'Sai Gon Pediatric Clinic',
        'address': '63 Lê Văn Duyệt, Phường 3, Quận Bình Thạnh, TP.HCM',
        'phone': '028 3843 9999',
        'hospital_type': 'clinic',
        'main_specialty': 'pediatrics',
        'specialties': ['pediatrics', 'vaccination', 'neonatology'],
        'emergency_services': False,
        'latitude': 10.7980,
        'longitude': 106.7000,
        'district': 'binhthanh',
        'working_hours': '07:30-17:30'
    },
    {
        'name': 'Phòng khám Sản Phụ khoa TPHCM',
        'name_en': 'HCMC Obstetrics Gynecology Clinic',
        'address': '350 Điện Biên Phủ, Phường 17, Quận Bình Thạnh, TP.HCM',
        'phone': '028 3516 6666',
        'hospital_type': 'clinic',
        'main_specialty': 'obstetrics',
        'specialties': ['obstetrics', 'gynecology', 'ultrasound'],
        'emergency_services': False,
        'latitude': 10.8030,
        'longitude': 106.7080,
        'district': 'binhthanh',
        'working_hours': '08:00-18:00'
    },
    {
        'name': 'Phòng khám Tim Mạch Sài Gòn',
        'name_en': 'Sai Gon Cardiology Clinic',
        'address': '88 Lê Lai, Phường Bến Thành, Quận 1, TP.HCM',
        'phone': '028 3929 1111',
        'hospital_type': 'clinic',
        'main_specialty': 'cardiology',
        'specialties': ['cardiology', 'ecg', 'holter'],
        'emergency_services': False,
        'latitude': 10.7720,
        'longitude': 106.6970,
        'district': 'quan1',
        'working_hours': '07:30-17:00'
    },
    {
        'name': 'Phòng khám Da liễu Central',
        'name_en': 'Central Dermatology Clinic',
        'address': '180 Nguyễn Thị Minh Khai, Phường 6, Quận 3, TP.HCM',
        'phone': '028 3930 4567',
        'hospital_type': 'clinic',
        'main_specialty': 'dermatology',
        'specialties': ['dermatology', 'laser', 'cosmetology'],
        'emergency_services': False,
        'latitude': 10.7810,
        'longitude': 106.6920,
        'district': 'quan3',
        'working_hours': '08:00-18:00'
    },
    {
        'name': 'Phòng khám Răng Hàm Mặt Quốc tế',
        'name_en': 'International Dental Clinic',
        'address': '55 Đường 3/2, Phường 11, Quận 10, TP.HCM',
        'phone': '028 3968 7777',
        'hospital_type': 'clinic',
        'main_specialty': 'dentistry',
        'specialties': ['dentistry', 'orthodontics', 'implant'],
        'emergency_services': False,
        'latitude': 10.7710,
        'longitude': 106.6810,
        'district': 'quan10',
        'working_hours': '08:00-19:00'
    },
    {
        'name': 'Phòng khám Mắt Sài Gòn',
        'name_en': 'Sai Gon Eye Clinic',
        'address': '99 Nguyễn Trãi, Phường Nguyễn Cư Trinh, Quận 1, TP.HCM',
        'phone': '028 3926 5555',
        'hospital_type': 'clinic',
        'main_specialty': 'ophthalmology',
        'specialties': ['ophthalmology', 'glasses', 'cataract'],
        'emergency_services': False,
        'latitude': 10.7650,
        'longitude': 106.6880,
        'district': 'quan1',
        'working_hours': '08:00-17:30'
    },
    {
        'name': 'Phòng khám Tai Mũi Họng Sài Gòn',
        'name_en': 'Sai Gon ENT Clinic',
        'address': '120 Nguyễn Trãi, Phường 2, Quận 5, TP.HCM',
        'phone': '028 3923 8888',
        'hospital_type': 'clinic',
        'main_specialty': 'ent',
        'specialties': ['ent', 'endoscopy', 'allergy'],
        'emergency_services': False,
        'latitude': 10.7590,
        'longitude': 106.6730,
        'district': 'quan5',
        'working_hours': '07:30-17:00'
    },
    {
        'name': 'Phòng khám Thần kinh Sài Gòn',
        'name_en': 'Sai Gon Neurology Clinic',
        'address': '180 Bạch Đằng, Phường 24, Quận Bình Thạnh, TP.HCM',
        'phone': '028 3517 8888',
        'hospital_type': 'clinic',
        'main_specialty': 'neurology',
        'specialties': ['neurology', 'eeg', 'emg'],
        'emergency_services': False,
        'latitude': 10.8000,
        'longitude': 106.7050,
        'district': 'binhthanh',
        'working_hours': '08:00-17:00'
    },
    {
        'name': 'Phòng khám Xương Khớp Sài Gòn',
        'name_en': 'Sai Gon Orthopedics Clinic',
        'address': '250 Lê Văn Sỹ, Phường 14, Quận 3, TP.HCM',
        'phone': '028 3930 6666',
        'hospital_type': 'clinic',
        'main_specialty': 'orthopedics',
        'specialties': ['orthopedics', 'arthritis', 'physiotherapy'],
        'emergency_services': False,
        'latitude': 10.7880,
        'longitude': 106.6850,
        'district': 'quan3',
        'working_hours': '07:30-17:00'
    },
    {
        'name': 'Phòng khám Tiêu Hóa Sài Gòn',
        'name_en': 'Sai Gon Gastroenterology Clinic',
        'address': '160 Hùng Vương, Phường 9, Quận 5, TP.HCM',
        'phone': '028 3955 9999',
        'hospital_type': 'clinic',
        'main_specialty': 'gastroenterology',
        'specialties': ['gastroenterology', 'endoscopy', 'ultrasound'],
        'emergency_services': False,
        'latitude': 10.7580,
        'longitude': 106.6680,
        'district': 'quan5',
        'working_hours': '07:00-17:00'
    },
    {
        'name': 'Phòng khám Đa khoa Quốc tế Sài Gòn',
        'name_en': 'Sai Gon International Clinic',
        'address': '1-3 Đường 3/2, Phường 11, Quận 10, TP.HCM',
        'phone': '028 3927 9999',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology', 'pediatrics'],
        'emergency_services': False,
        'latitude': 10.7720,
        'longitude': 106.6820,
        'district': 'quan10',
        'working_hours': '07:00-20:00'
    },
    {
        'name': 'Phòng khám Đa khoa Hoàng Gia',
        'name_en': 'Hoang Gia General Clinic',
        'address': '88 Nguyễn Ảnh Thủ, Phường Trung Mỹ Tây, Quận 12, TP.HCM',
        'phone': '028 6256 6666',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'ultrasound'],
        'emergency_services': False,
        'latitude': 10.8620,
        'longitude': 106.6150,
        'district': 'quan12',
        'working_hours': '07:00-18:00'
    },
    {
        'name': 'Phòng khám Đa khoa Bình Dương',
        'name_en': 'Binh Duong General Clinic',
        'address': '256 Phan Văn Hớn, Phường Bình Hưng Hòa A, Quận Bình Tân, TP.HCM',
        'phone': '028 3765 8888',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'health_check'],
        'emergency_services': False,
        'latitude': 10.7800,
        'longitude': 106.5850,
        'district': 'binhtan',
        'working_hours': '07:30-17:00'
    },
    {
        'name': 'Phòng khám Đa khoa Minh Khang',
        'name_en': 'Minh Khang General Clinic',
        'address': '188 Quốc lộ 1A, Phường Bình Trị Đông, Quận Bình Tân, TP.HCM',
        'phone': '028 3763 9999',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology'],
        'emergency_services': False,
        'latitude': 10.7700,
        'longitude': 106.5950,
        'district': 'binhtan',
        'working_hours': '07:00-17:30'
    },
    {
        'name': 'Phòng khám Đa khoa Phú Thọ',
        'name_en': 'Phu Tho General Clinic',
        'address': '145 Hoàng Văn Thụ, Phường 8, Quận Phú Nhuận, TP.HCM',
        'phone': '028 3991 8888',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'pediatrics'],
        'emergency_services': False,
        'latitude': 10.7940,
        'longitude': 106.6720,
        'district': 'phunhuan',
        'working_hours': '07:30-17:00'
    },
    {
        'name': 'Phòng khám Đa khoa Đại Việt',
        'name_en': 'Dai Viet General Clinic',
        'address': '268 Lê Văn Sỹ, Phường 14, Quận 3, TP.HCM',
        'phone': '028 3932 7777',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'ultrasound', 'ecg'],
        'emergency_services': False,
        'latitude': 10.7880,
        'longitude': 106.6860,
        'district': 'quan3',
        'working_hours': '08:00-17:00'
    },
    {
        'name': 'Phòng khám Đa khoa Thăng Long',
        'name_en': 'Thang Long General Clinic',
        'address': '165 Nguyễn Văn Cừ, Phường 2, Quận 5, TP.HCM',
        'phone': '028 3838 9999',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'health_check'],
        'emergency_services': False,
        'latitude': 10.7620,
        'longitude': 106.6800,
        'district': 'quan5',
        'working_hours': '07:00-17:00'
    },
    {
        'name': 'Phòng khám Đa khoa Việt Hàn',
        'name_en': 'Viet Han General Clinic',
        'address': '123 Nguyễn Trọng Tuyển, Phường 15, Quận Phú Nhuận, TP.HCM',
        'phone': '028 3990 3333',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'dermatology'],
        'emergency_services': False,
        'latitude': 10.7960,
        'longitude': 106.6780,
        'district': 'phunhuan',
        'working_hours': '07:30-17:00'
    },
    {
        'name': 'Phòng khám Đa khoa Đông Nam',
        'name_en': 'Dong Nam General Clinic',
        'address': '58 Phổ Quang, Phường 2, Quận Tân Bình, TP.HCM',
        'phone': '028 3845 8888',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'cardiology'],
        'emergency_services': False,
        'latitude': 10.8020,
        'longitude': 106.6620,
        'district': 'tanbinh',
        'working_hours': '07:00-17:00'
    },
    {
        'name': 'Phòng khám Đa khoa Hòa Bình',
        'name_en': 'Hoa Binh General Clinic',
        'address': '75 Bàu Cát, Phường 14, Quận Tân Bình, TP.HCM',
        'phone': '028 3848 6666',
        'hospital_type': 'clinic',
        'main_specialty': 'general',
        'specialties': ['general', 'pediatrics'],
        'emergency_services': False,
        'latitude': 10.7900,
        'longitude': 106.6550,
        'district': 'tanbinh',
        'working_hours': '07:30-17:00'
    },

]

# Xóa dữ liệu cũ
Hospital.objects.all().delete()

# Thêm dữ liệu mới
created_count = 0
for h in hospitals_data:
    try:
        Hospital.objects.create(**h)
        created_count += 1
    except Exception as e:
        print(f'Lỗi tạo "{h["name"]}": {e}')

print(f'Done. Created {created_count}/{len(hospitals_data)}')
