"""
Django settings for hospital_locator project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dzt=j8smkyogx19v=&t0s1nrgenh7j*cq)bv*=(6f&=31y2geq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allow all hosts for development (CORS will handle access control)
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'hospitals',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# CORS Configuration - Cho phép frontend truy cập API
CORS_ALLOW_ALL_ORIGINS = True  # Development only!
# Hoặc chỉ định cụ thể:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
# ]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Thư mục static cho admin custom
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# GIS Configuration for Windows
import os
if os.name == 'nt':
    import sys
    from pathlib import Path
    
    # Try multiple locations for GDAL
    possible_paths = [
        Path(__file__).resolve().parent.parent.parent.parent / 'Lib' / 'site-packages' / 'osgeo',  # venv
        Path('C:/OSGeo4W64/bin'),  # OSGeo4W 64-bit
        Path('C:/OSGeo4W/bin'),    # OSGeo4W 32-bit
        Path('C:/Program Files/GDAL'),  # Common install location
        Path('C:/Program Files (x86)/GDAL'),
    ]
    
    gdal_found = False
    for GDAL_PATH in possible_paths:
        if GDAL_PATH.exists():
            gdal_dll = GDAL_PATH / 'gdal307.dll'
            geos_dll = GDAL_PATH / 'geos_c.dll'
            
            if gdal_dll.exists() or geos_dll.exists():
                os.environ['PATH'] = str(GDAL_PATH) + ';' + os.environ['PATH']
                if (GDAL_PATH / 'data').exists():
                    os.environ['PROJ_LIB'] = str(GDAL_PATH / 'data')
                if gdal_dll.exists():
                    os.environ['GDAL_LIBRARY_PATH'] = str(gdal_dll)
                if geos_dll.exists():
                    os.environ['GEOS_LIBRARY_PATH'] = str(geos_dll)
                gdal_found = True
                break
    
    if not gdal_found:
        # Try system PATH
        for path in os.environ.get('PATH', '').split(';'):
            p = Path(path)
            if (p / 'gdal307.dll').exists() or (p / 'gdalXXX.dll').exists():
                os.environ['GDAL_LIBRARY_PATH'] = str(p / 'gdal307.dll')
                break
