# Generated by Django 5.2.9 on 2026-01-29 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên bệnh viện')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Tên tiếng Anh')),
                ('hospital_type', models.CharField(choices=[('public', 'Công lập'), ('private', 'Tư nhân'), ('clinic', 'Phòng khám')], default='public', max_length=20, verbose_name='Loại bệnh viện')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('district', models.CharField(choices=[('quan1', 'Quận 1'), ('quan2', 'Quận 2'), ('quan3', 'Quận 3'), ('quan4', 'Quận 4'), ('quan5', 'Quận 5'), ('quan6', 'Quận 6'), ('quan7', 'Quận 7'), ('quan8', 'Quận 8'), ('quan9', 'Quận 9'), ('quan10', 'Quận 10'), ('quan11', 'Quận 11'), ('quan12', 'Quận 12'), ('binhthanh', 'Quận Bình Thạnh'), ('govap', 'Quận Gò Vấp'), ('phunhuan', 'Quận Phú Nhuận'), ('tanbinh', 'Quận Tân Bình'), ('tanphu', 'Quận Tân Phú'), ('thuduc', 'Quận Thủ Đức'), ('binhtan', 'Quận Bình Tân'), ('hocmon', 'Huyện Hóc Môn'), ('cuchi', 'Huyện Củ Chi'), ('nhabbe', 'Huyện Nhà Bè'), ('canggio', 'Huyện Cần Giờ')], max_length=20, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Phường/Xã')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('main_specialty', models.CharField(choices=[('general', 'Đa khoa'), ('pediatrics', 'Nhi'), ('obstetrics', 'Sản'), ('cardiology', 'Tim mạch'), ('oncology', 'Ung bướu'), ('neurology', 'Thần kinh'), ('orthopedics', 'Chỉnh hình'), ('ophthalmology', 'Mắt'), ('dentistry', 'Răng hàm mặt'), ('dermatology', 'Da liễu')], default='general', max_length=20, verbose_name='Chuyên khoa chính')),
                ('specialties', models.JSONField(blank=True, default=list, verbose_name='Các chuyên khoa')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ')),
                ('working_hours', models.JSONField(blank=True, default=dict, verbose_name='Giờ làm việc')),
                ('emergency_services', models.BooleanField(default=False, verbose_name='Có cấp cứu')),
                ('ambulance_services', models.BooleanField(default=False, verbose_name='Có xe cứu thương')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sức chứa giường bệnh')),
                ('doctors_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số bác sĩ')),
                ('nurses_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số y tá')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Bệnh viện',
                'verbose_name_plural': 'Bệnh viện',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['hospital_type'], name='hospitals_h_hospita_acbdf6_idx'), models.Index(fields=['district'], name='hospitals_h_distric_34c27b_idx'), models.Index(fields=['main_specialty'], name='hospitals_h_main_sp_300f72_idx'), models.Index(fields=['latitude', 'longitude'], name='hospitals_h_latitud_e7780c_idx')],
            },
        ),
        migrations.CreateModel(
            name='HospitalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hospitals/', verbose_name='Hình ảnh')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('is_main', models.BooleanField(default=False, verbose_name='Ảnh chính')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hospitals.hospital')),
            ],
            options={
                'verbose_name': 'Hình ảnh bệnh viện',
                'verbose_name_plural': 'Hình ảnh bệnh viện',
            },
        ),
    ]
