# Generated by Django 5.2.9 on 2026-01-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalImage',
        ),
    ]
